// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.daigham.EtudeDeCas.stub;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string nom = 2;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string prenom = 3;</code>
   * @return The prenom.
   */
  java.lang.String getPrenom();
  /**
   * <code>string prenom = 3;</code>
   * @return The bytes for prenom.
   */
  com.google.protobuf.ByteString
      getPrenomBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string telephone = 5;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>string telephone = 5;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();
}
