// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.daigham.EtudeDeCas.stub;

public interface DeleteReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.DeleteReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
