// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.daigham.EtudeDeCas.stub;

public interface ReservationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.ReservationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  java.util.List<Reservation>
      getReservationsList();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  Reservation getReservations(int index);
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  java.util.List<? extends ReservationOrBuilder>
      getReservationsOrBuilderList();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
