// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.daigham.EtudeDeCas.stub;

public interface UpdateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.UpdateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.com.chalabi.EtudeDeCas.Reservation reservation = 2;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.com.chalabi.EtudeDeCas.Reservation reservation = 2;</code>
   * @return The reservation.
   */
  Reservation getReservation();
  /**
   * <code>.com.chalabi.EtudeDeCas.Reservation reservation = 2;</code>
   */
  ReservationOrBuilder getReservationOrBuilder();
}
